version: "3"
services:
  main_app:
    build: .
    container_name: "checkers_main"
    restart: unless-stopped
    networks:
      - queue_net
    depends_on:
      - rabbitmq
    volumes:
      - ../app:/app
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: grid
      RABBITMQ_DEFAULT_PASS: cloud
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - queue_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1

networks:
  queue_net:
    driver: bridge