version: "3"
services:
   worker_app:
     build:
       dockerfile: ../docker/computational_app/Dockerfile
       context: ../app
     container_name: "checkers_main"
     restart: unless-stopped
     networks:
       - queue_net
     depends_on:
       - rabbitmq
     volumes:
       - ../app:/app
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: grid
      RABBITMQ_DEFAULT_PASS: cloud
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - queue_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1
  api:
    build:
      dockerfile: ../docker/api_app/Dockerfile
      context: ../api
    container_name: "api"
    restart: unless-stopped
    networks:
      - queue_net
      - front_net
    depends_on:
      - rabbitmq
    volumes:
      - ../api:/app
  front: 
    build:
      dockerfile: ../docker/front/Dockerfile
      context: ../frontend
    depends_on:
      - api
    ports:
      - "4200:4200"
    networks:
      - front_net
    volumes:
      - ../frontend:/app



networks:
  queue_net:
    driver: bridge
  front_net:
    driver: bridge